language: scala

scala:
  - 2.12.12

jdk:
  - openjdk11

sudo: false
addons:
  apt:
    packages:
      - graphviz

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

jobs:
  include:
    - scala: 2.12.12 # Remember to update this in build.sbt, too.
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test